export default {
  login: "purunep",
  id: 1876638,
  node_id: "MDQ6VXNlcjE4NzY2Mzg=",
  avatar_url: "https://avatars.githubusercontent.com/u/1876638?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/purunep",
  html_url: "https://github.com/purunep",
  followers_url: "https://api.github.com/users/purunep/followers",
  following_url: "https://api.github.com/users/purunep/following{/other_user}",
  gists_url: "https://api.github.com/users/purunep/gists{/gist_id}",
  starred_url: "https://api.github.com/users/purunep/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/purunep/subscriptions",
  organizations_url: "https://api.github.com/users/purunep/orgs",
  repos_url: "https://api.github.com/users/purunep/repos",
  events_url: "https://api.github.com/users/purunep/events{/privacy}",
  received_events_url: "https://api.github.com/users/purunep/received_events",
  type: "User",
  site_admin: false,
  name: "Puru",
  company: "Private",
  blog: "purunep.wordpress.com",
  location: "Toronto, Canada",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: "purunep",
  public_repos: 11,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2012-06-21T11:58:07Z",
  updated_at: "2021-07-19T13:23:33Z",
};
